from . import account_analytic_account
from . import sale_order
from . import res_partner_inherit
from . import product_template
from . import account_payment_register
from . import account_move
from . import account_move_line
from . import sale_order_line
from . import sale_subscription